[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad para tu aplicación
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      # Scripts permitidos (Google Analytics + Google Maps)
      script-src 'self' 'unsafe-inline' 'unsafe-eval'
        https://www.googletagmanager.com
        https://www.google-analytics.com
        https://maps.googleapis.com
        https://maps.gstatic.com;
      script-src-elem 'self'
        https://www.googletagmanager.com
        https://www.google-analytics.com
        https://maps.googleapis.com
        https://maps.gstatic.com;
      # Estilos (Google Fonts + estilos de Maps)
      style-src 'self' 'unsafe-inline'
        https://fonts.googleapis.com
        https://maps.gstatic.com;
      style-src-elem 'self' 'unsafe-inline'
        https://fonts.googleapis.com
        https://maps.gstatic.com;
      # Fuentes
      font-src 'self' https://fonts.gstatic.com data:;
      # Imágenes (incluye tiles y recursos de Google Maps)
      img-src 'self' data: blob: https:
        https://maps.gstatic.com
        https://maps.googleapis.com
        https://maps.google.com
        https://lh3.googleusercontent.com;
      # Conexiones (para Analytics y Maps API)
      connect-src 'self'
        https://www.google-analytics.com
        https://maps.googleapis.com
        https://maps.gstatic.com;
      # iframes (para Google Maps embebidos)
      frame-src 'self' https://www.google.com https://www.google.es;
      # Service workers / blobs
      worker-src 'self' blob:;
      # Restricciones adicionales
      object-src 'none';
      base-uri 'self';
      frame-ancestors 'self';
      upgrade-insecure-requests;
    """

# Cache control para assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
