[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cabeceras de seguridad (comentarios fuera del valor de CSP)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # IMPORTANTE: no incluyas líneas que empiecen por # dentro del valor multi-línea de CSP
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://maps.googleapis.com https://maps.gstatic.com;
      script-src-elem 'self' https://www.googletagmanager.com https://www.google-analytics.com https://maps.googleapis.com https://maps.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://maps.gstatic.com;
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com https://maps.gstatic.com;
      font-src 'self' https://fonts.gstatic.com data:;
      img-src 'self' data: blob: https: https://maps.gstatic.com https://maps.googleapis.com https://maps.google.com https://lh3.googleusercontent.com;
      connect-src 'self' https://www.google-analytics.com https://maps.googleapis.com https://maps.gstatic.com https://fonts.googleapis.com;
      frame-src 'self' https://www.google.com https://www.google.es;
      worker-src 'self' blob:;
      object-src 'none';
      base-uri 'self';
      frame-ancestors 'self';
      upgrade-insecure-requests;
    """

# Cache de estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control =  "no-cache"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control =  "no-cache"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control =  "no-cache"
